package main

var templateTemplatesRegisterTmpl = `
<form action="/register" class="form-horizontal ajax-submit" method="post">
	<div class="form-group">
		<label for="email" class="col-sm-2 control-label">Email</label>
		<div class="col-sm-10">
			<input type="email" name="email" id="inputEmail" class="form-control" required>
		</div>
	</div>
	<div class="form-group">
		<label for="password" class="col-sm-2 control-label">Password</label>
		<div class="col-sm-10">
			<input type="password" name="password" id="inputPassword" class="form-control" required>
		</div>
	</div>
	<div class="form-group">
		<label for="passwordConfirm" class="col-sm-2 control-label">Password Repeat</label>
		<div class="col-sm-10">
			<input type="password" name="password_repeat" id="inputPasswordConfirm" class="form-control" required>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<input type="submit" value="Register" class="btn btn-primary pull-right">
		</div>
	</div>
</form>
`

var templateTemplatesLoginTmpl = `
<form action="/login" class="form-horizontal ajax-submit" method="post">
	<div class="form-group">
		<label for="email" class="col-sm-2 control-label">Email</label>
		<div class="col-sm-10">
			<input type="email" name="email" id="inputEmail" class="form-control" required>
		</div>
	</div>
	<div class="form-group">
		<label for="password" class="col-sm-2 control-label">Password</label>
		<div class="col-sm-10">
			<input type="password" name="password" id="inputPassword" class="form-control" required>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<input type="submit" value="Login" class="btn btn-primary pull-right">
		</div>
	</div>
</form>
`

var templateTemplatesGeneratedLeftNavTmpl = `
<!-- Do not edit this file, it's automatically generated and contents can be overwritten at any time -->
<li [[ if eq .CurrentPage "home" ]]class="active"[[ end ]]><a href="/">Home</a></li>
<li [[ if eq .CurrentPage "about" ]]class="active"[[ end ]]><a href="/about">About</a></li>
`

var templateTemplatesHomeTmpl = `
<div class="row">
	<div class="col-sm-12">
		Welcome to [[ .AppName ]]!
	</div>
</div>
`

var templateTemplatesLayoutTmpl = `
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

	<style>
	body { padding-top:60px; }
	</style>
</head>
<body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">[[ .AppName ]]</a>
	    </div>
	    <div id="navbar" class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
	        [[ template "generated_left_nav" . ]]
	      </ul>
	      {{ if ne .Config.LoginCrud "" }}
	      <ul class="nav navbar-nav navbar-right">
	      	[[ if eq .LoggedIn.ID 0 ]]
	      	[[ if eq .AllowRegistration true ]]
			<li>
				<a href="" type="button" data-toggle="modal" data-target="#Register">Register</a>
			</li>
	      	[[ end ]]
			<li>
				<a href="" type="button" data-toggle="modal" data-target="#Login">Login</a>
			</li>
			[[ else ]]
			<li>
				<p class="navbar-text">[[ .LoggedIn.Email ]]</p>
			</li>
			<li>
				<a href="/logout">Logout</a>
			</li>
			[[ end ]]
	      </ul>
	      {{ end }}
	    </div><!--/.nav-collapse -->
	  </div>
	</nav>

	<div class="container">
		[[ .LoggedIn.ID ]]
	</div>

	<div class="container">
		[[ yield ]]
	</div>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

	[[ template "siteModals" . ]]
</body>
</html>
`

var templateTemplatesSiteModalsTmpl = `
{{ if ne .Config.LoginCrud "" }}
<div class="modal fade" id="Register" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span>&times;</span>
				</button>
				<h4 class="modal-title" id="RegisterLabel">Register</h4>
			</div>
			<div class="modal-body">
				[[ template "Register" . ]]
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="Login" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span>&times;</span>
				</button>
				<h4 class="modal-title" id="LoginLabel">Login</h4>
			</div>
			<div class="modal-body">
				[[ template "Login" . ]]
			</div>
		</div>
	</div>
</div>

<script>
	$(function() {
		var formPost = function(uri, sendData) {
			$.post(uri, sendData, function() {})
			.done(function() {
				location.reload();
			}).fail(function(data) {
				alert(data.responseText)
			})
		}
		$("form.ajax-submit").submit(function(e) {
			console.info('hi');
			e.preventDefault()

			$form = $(this);
			formPost($form.attr('action'), $form.serialize());
		});
	})
</script>
{{ end }}
`
